UI/WebStore/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using WebStore.Domain;
using WebStore.Domain.DTO.Catalog;
using WebStore.Domain.Entities;
using WebStore.Domain.Models;
using WebStore.Interfaces.Services;
using WebStore.Services.Mapping;

namespace WebStore.Controllers
{
    public class CatalogController : Controller
    {
        private readonly ICatalogData _catalogData;
        private readonly IConfiguration _configuration;
        private const string PAGE_SIZE = "PageSize";

        public CatalogController(ICatalogData catalogData, IConfiguration configuration)
        {
            _catalogData = catalogData;
            _configuration = configuration;
        }

        public IActionResult Shop(int? sectionId, int? brandId, int page = 1)
        {
            int? pageSize = int.TryParse(_configuration[PAGE_SIZE], out int page_size) ? page_size : (int?)null;

            PageProductsDTO products = _catalogData.GetProducts(new ProductFilter
            {
                BrandId = brandId,
                SectionId = sectionId,
                Page = page,
                PageSize = pageSize
            });

            CatalogViewModel catalogViewModel = new CatalogViewModel
            {
                BrandId = brandId,
                SectionId = sectionId,
                Products = products.Products.FromDTO().ToView(),
                PageViewModel = new PageViewModel()
                {
                    PageNumber = page,
                    TotalItems = products.TotalCount,
                    PageSize = pageSize.GetValueOrDefault()
                }
            };

            return View(catalogViewModel);
        }

        public IActionResult ProductDetails(int productId)
        {
            ProductDTO product = _catalogData.GetProductById(productId);
            if (product == null) return NotFound();
            return View(product.FromDTO().ToView());
        }


        #region API

        public IActionResult GetFilteredItems(int? sectionId, int? brandId, int page)
        {
            ProductFilter productFilter = new ProductFilter()
            {
                SectionId = sectionId,
                BrandId = brandId,
                Page = page,
                PageSize = int.Parse(_configuration[PAGE_SIZE])
            };

            IEnumerable<ProductViewModel> products = _catalogData.GetProducts(productFilter).Products
                .FromDTO()  //ProductDTO => Product
                .ToView()   //Product => ProductViewModel
                .OrderBy(p => p.Order);

            return PartialView("Partial/_ProductItems", products);
        }

        #endregion
    }
}

UI/WebStore/Controllers/ProfileController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebStore.Domain.Models;
using WebStore.Interfaces.Services;

namespace WebStore.Controllers
{
    [Authorize]
    public class ProfileController : Controller
    {
        ISqlOrderService _sqlOrderService;

        public ProfileController(ISqlOrderService sqlOrderService)
        {
            _sqlOrderService = sqlOrderService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Orders()
        {
            IEnumerable<UserOrderViewModel> orders = _sqlOrderService.GetUserOrders(User.Identity.Name)
                .Select(order => new UserOrderViewModel()
                {
                    OrderNumber = order.Id,
                    Name = order.UserName,
                    Address = order.Address,
                    Phone = order.Phone,
                    TotalSum = order.TotalPrice
                });
            return View(orders);
        }
    }
}

UI/WebStore/Views/Shared/_Footer.cshtml
<footer id="footer">
    <!--Footer-->
    <div class="footer-top">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="companyinfo">
                        <h2><span>e</span>-shopper</h2>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit,sed do eiusmod tempor</p>
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe1.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe2.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe3.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <div class="video-gallery text-center">
                            <a href="#">
                                <div class="iframe-img">
                                    <img src="~/images/home/iframe4.png" alt="" />
                                </div>
                                <div class="overlay-icon">
                                    <i class="fa fa-play-circle-o"></i>
                                </div>
                            </a>
                            <p>Circle of Hands</p>
                            <h2>24 DEC 2014</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="address">
                        <img src="~/images/home/map.png" alt="" />
                        <p>505 S Atlantic Ave Virginia Beach, VA(Virginia)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-widget">
        <div class="container">
            <div class="row">
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Service</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Online Help</a></li>
                            <li><a href="#">Contact Us</a></li>
                            <li><a href="#">Order Status</a></li>
                            <li><a href="#">Change Location</a></li>
                            <li><a href="#">FAQ’s</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Quock Shop</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">T-Shirt</a></li>
                            <li><a href="#">Mens</a></li>
                            <li><a href="#">Womens</a></li>
                            <li><a href="#">Gift Cards</a></li>
                            <li><a href="#">Shoes</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>Policies</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Terms of Use</a></li>
                            <li><a href="#">Privecy Policy</a></li>
                            <li><a href="#">Refund Policy</a></li>
                            <li><a href="#">Billing System</a></li>
                            <li><a href="#">Ticket System</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <ul class="nav nav-pills nav-stacked">
                            <li><a href="#">Company Information</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="#">Store Location</a></li>
                            <li><a href="#">Affillate Program</a></li>
                            <li><a href="#">Copyright</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 col-sm-offset-1">
                    <div class="single-widget">
                        <h2>About Shopper</h2>
                        <form action="#" class="searchform">
                            <input type="text" placeholder="Your email address" />
                            <button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
                            <p>Get the most recent updates from <br />our site and be updated your self...</p>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <p class="pull-left">Copyright © 2013 E-SHOPPER Inc. All rights reserved.</p>
                <p class="pull-right">Designed by <span><a target="_blank" href="http://www.themeum.com">Themeum</a></span></p>
            </div>
        </div>
    </div>

</footer><!--/Footer-->

UI/WebStore/Views/Shared/_Header.cshtml
<header id="header">
    <!--header-->
    <div class="header_top">
        <!--header_top-->
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="contactinfo">
                        <ul class="nav nav-pills">
                            <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
                            <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="social-icons pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header_top-->

    <div class="header-middle">
        <!--header-middle-->
        <div class="container">
            <div class="row">
                <div class="col-sm-4">
                    <div class="logo pull-left">
                        <a asp-controller="home" asp-action="index"><img src="~/images/home/logo.png" alt="" /></a>
                    </div>
                    <div class="btn-group pull-right">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                USA
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canada</a></li>
                                <li><a href="#">UK</a></li>
                            </ul>
                        </div>

                        <div class="btn-group">
                            <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                                DOLLAR
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu">
                                <li><a href="#">Canadian Dollar</a></li>
                                <li><a href="#">Pound</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6">
                    <div class="shop-menu pull-right">
                        <ul class="nav navbar-nav">
                            <li>
                                <div class="pull-right" id="cart-container"><vc:cart/></div>
                                @*<a asp-controller="Cart" asp-action="Cart"><i class="fa fa-shopping-cart"></i> Корзина</a>*@
                            </li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li><a asp-controller="Profile" asp-action="Index"><i class="fa fa-user"></i> Личный кабинет</a></li>
                            }
                            @if (User.IsInRole("Admins"))
                            {
                                <li><a asp-area="Admin" asp-controller="Home" asp-action="Index"><i class="fa fa-gear"></i> Админка</a></li>
                            }
                        </ul>
                    </div>
                </div>
                <div>
                    @await Component.InvokeAsync("LoginLogout")
                    @*<vc:login-logout></vc:login-logout>*@@*<=> LoginLogout*@
                </div>
            </div>
        </div>
    </div><!--/header-middle-->

    <div class="header-bottom">
        <!--header-bottom-->
        <div class="container">
            <div class="row">
                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="mainmenu pull-left">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a asp-controller="home" asp-action="index" class="@IsActive("Home", "Index")">Главная</a></li>
                            <li><a asp-controller="Catalog" asp-action="Shop" class="@IsActive("Catalog", "Shop")">Магазин</a></li>
                            <li class="dropdown">
                                <a href="#">Shop<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a asp-controller="home" asp-action="CheckoutExample">CheckoutExample</a></li>
                                    <li><a asp-controller="home" asp-action="CartExample">CartExample</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a asp-controller="blogs" is-active-route ignore-action>Blog<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a asp-controller="blogs" asp-action="Index">Blog List</a></li>
                                    <li><a asp-controller="blogs" asp-action="BlogSingle">Blog Single</a></li>
                                </ul>
                            </li>
                            <li><a asp-controller="home" asp-action="NotFound404">404</a></li>
                            <li><a asp-controller="home" asp-action="ContactUs" class="@IsActive("Home", "ContactUs")">Contact</a></li>
                            <li><a asp-controller="Employee" asp-action="Employees" class="@IsActive("Employee", "Employees")">Employees</a></li>
                            <li class="dropdown">
                                <a ignore-action href="#">Тест<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a is-active-route asp-controller="AjaxTest" asp-action="Index">AJAX</a></li>
                                    <li><a is-active-route asp-controller="AjaxTest" asp-action="SignalRTest">SignalR</a></li>
                                    <li><a is-active-route asp-controller="WebAPITest" asp-action="Index" class="@IsActive("WebAPITest", "Index")">WebAPI</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3">
                    <div class="search_box pull-right">
                        <input type="text" placeholder="Search" />
                    </div>
                </div>
            </div>
        </div>
    </div><!--/header-bottom-->
</header><!--/header-->


@functions{ //Раздел для методов, которые будут выполняться во время загрузки страницы

string IsActive(string controllerName, string actionName) //для подсветки активных ссылок
{
    if (Equals(controllerName, ViewContext.RouteData.Values["Controller"]) && Equals(actionName, ViewContext.RouteData.Values["Action"])) return "active";
    else return null;
}

}

UI/WebStore/Views/Shared/_Layout.cshtml
@*Мастер-страница - содержит разметку header, footer, menu  итд (то, что повторяется на всех страницах)*@

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    @*Вставка названия вкладки*@
    <title>@ViewData["Title"]</title>

    <environment include="Development"> @* в режиме разработки (Properties=> Debug=> ASPNETCORE_ENVIRONMENT=Development) подключать обычные css файлы *@
        <link href="~/css/prettyPhoto.css" rel="stylesheet">
        <link href="~/css/price-range.css" rel="stylesheet">
        <link href="~/css/animate.css" rel="stylesheet">
        <link href="~/css/responsive.css" rel="stylesheet">
    </environment>
    <environment exclude="Development">
        @* иначе подключать минимизированный css (в который собраны предыдущие файлы)*@
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" /> @* append-version для отслеживания версии файла браузером и своевременного его обновления в кэше при изменении файла *@
    </environment>

    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/css/main.css" rel="stylesheet" asp-append-version="true">

    <!--[if lt IE 9]>
    <script src="~/js/html5shiv.js"></script>
    <script src="~/js/respond.min.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="~/images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/images/ico/apple-touch-icon-57-precomposed.png">

</head><!--/head-->
<body>
    @await Html.PartialAsync("_Header")
    <div>
        @*Вставка контента страницы*@
        @RenderBody()
    </div>
    @await Html.PartialAsync("_Footer")

    <environment include="Development">
        <script src="~/js/price-range.js"></script>
        <script src="~/js/jquery.prettyPhoto.js"></script>
        <script src="~/js/main.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.scrollUp.min.js"></script>


    <script src="~/js/Cart/CartLogic.js" asp-append-version="true"></script> @*подключаем наш скрипт для работы с элементами корзины*@
    <script>                                                                //и здесь же конфигурируем его
    $(function () {
        Cart.init({
            getCartViewLink: "@Url.Action("GetCartView", "Cart")",          //каждому свойству скрипта передаем ссылку на контроллер и определенный метод
            addToCartLink: "@Url.Action("AddToCartAPI", "Cart")",
            decrementLink: "@Url.Action("DecrementFromCartAPI", "Cart")",
            removeFromCartLink: "@Url.Action("RemoveFromCartAPI", "Cart")"
        });
    })
</script>



    <!--Секция для подгрузки кастомных скриптов, если понадобятся-->
    @await RenderSectionAsync("Scripts", false) @*параметр false означает, что секция не обязательна, т.е. если на какой-либо странице нет @section Scripts{...}, то ошибки не будет*@
</body>
</html>